# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-pfJHsLVxtDKaGsWhHOtm7FUp1XjhRL
"""

from fastapi import FastAPI, Request
import os
from supabase import create_client, Client
from predict_pipeline import predict_pipeline

# Load Supabase credentials from Cloud Run environment variables
SUPABASE_URL = os.environ["https://paalbwihwwiynooldohn.supabase.co"]
SUPABASE_SERVICE_KEY = os.environ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYWxid2lod3dpeW5vb2xkb2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzk3MDcsImV4cCI6MjA4MDk1NTcwN30.kXDShSLpzM3imDXc_1rn-TzzXt10PpSWTsRtCxGdedM"]

supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

app = FastAPI()

@app.post("/run")
async def run_model(req: Request):
    body = await req.json()

    # Extract your ID column
    row_id = body["order_id"]

    # Run the ML model
    prediction = predict_pipeline(body)

    # Update Supabase: write the result into fraud_label column
    supabase.table("return1_data").update({
        "fraud_label": prediction
    }).eq("order_id", row_id).execute()

    return {"status": "ok", "order_id": row_id, "prediction": prediction}